# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  tox:
    docker:
      - image: ttwshell/pyenv-tox:latest
        user: root
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: hobbit_core
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hobbit_core
          MYSQL_PORT: 3306
    working_directory: ~/repo
    steps:
      - run: pyenv global 3.10.0 py36 py37 py38 py39 py310
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: sleep 10
      - run:
          command: pip install codecov
      - run:
          command: |
            tox -- --cov-report=xml
            codecov

  test-py36:
    docker:
      - image: circleci/python:3.6.13
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov pytest-env
            pip install --editable ".[hobbit,hobbit_core]"
            pip install celery
            pip install "MarkupSafe==2.0.1" blinker[flask]
      - run:
          name: use flake8 check self
          command: flake8 .
      - run:
          name: run hobbit cmd
          command: hobbit --echo startproject -n demo -d ~/haha -f -p 1024 --no-celery
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
      - run:
          name: run tests
          command: |
            cd ~/haha
            FLASK_APP=app.run:app flask db init && FLASK_APP=app.run:app flask db migrate && FLASK_APP=app.run:app flask db upgrade
            flake8 . --exclude migrations
            py.test
  test-py37:
    docker:
      - image: circleci/python:3.7.10
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install flake8 pytest pytest-cov pytest-env
            pip install --editable ".[hobbit,hobbit_core]"
            pip install celery
            pip install "MarkupSafe==2.0.1" blinker[flask]
      - run:
          name: use flake8 check self
          command: flake8 .
      - run:
          name: run hobbit cmd
          command: |
            mkdir ~/haha && cd ~/haha
            hobbit --echo startproject -n demo -f -p 1024 --celery
            mkdir ~/hahaha && cd ~/hahaha
            hobbit --echo startproject -n demo -t rivendell -p 1025 --celery
      - run:
          name: tree flask project
          command: |
            cd ~/haha
            apt-get install -y tree
            tree
            cd ~/hahaha
            tree
      - run:
          name: run tests
          command: |
            cd ~/haha
            FLASK_APP=app.run:app flask db init && FLASK_APP=app.run:app flask db migrate && FLASK_APP=app.run:app flask db upgrade
            flake8 . --exclude migrations
            py.test
            cd ~/hahaha
            FLASK_APP=app.run:app flask db init && FLASK_APP=app.run:app flask db migrate && FLASK_APP=app.run:app flask db upgrade
            flake8 . --exclude migrations
            py.test

workflows:
  version: 2
  test:
    jobs:
      - tox
      - test-py36:
          requires:
            - tox
      - test-py37:
          requires:
            - tox
